[2015.7.2] [Python] Compute wire 'a' signal again
Struggled with LSHIFT lambda giving

    OverflowError: too many digits in integer

as following the puzzle word-for-word by first setting signal on wire
`b` first and then resetting the board leads to this as both inputs of
a LSHIFT gate was already loaded and pin choose logic fellback to pin
1 leading to 15 << 234881025.

Resetting everything and setting just `b`’s signal didn’t work too as
the result came to be 0; setting other inputs was required.